/* Rough calories/protein for common college foods (estimates — edit or add your own) */
'use strict';
const FOOD_CATS = ['Protein', 'Dining hall', 'Fast food', 'Breakfast', 'Snacks', 'Drinks'];
const FOODS = [
  // Protein staples
  ['whey', 'Whey shake (1 scoop, water)', 120, 24, 'Protein', 'veg'],
  ['premier', 'Premier Protein shake', 160, 30, 'Protein', 'veg'],
  ['corepower', 'Fairlife Core Power (26 g)', 170, 26, 'Protein', 'veg'],
  ['greekyog', 'Greek yogurt cup (nonfat)', 100, 16, 'Protein', 'veg'],
  ['oikospro', 'Oikos Pro yogurt', 140, 20, 'Protein', 'veg'],
  ['cottage', 'Cottage cheese (1 cup)', 180, 24, 'Protein', 'veg'],
  ['eggs3', 'Eggs ×3 (scrambled)', 270, 19, 'Protein', 'veg'],
  ['eggwhite', 'Egg whites (1 cup)', 125, 26, 'Protein', 'veg'],
  ['hbegg', 'Hard-boiled egg', 78, 6, 'Protein', 'veg'],
  ['chicken6', 'Grilled chicken breast (6 oz)', 280, 52, 'Protein', 'meat'],
  ['beef93', 'Lean ground beef 93% (4 oz)', 170, 23, 'Protein', 'meat'],
  ['salmon', 'Salmon (5 oz)', 290, 32, 'Protein', 'fish'],
  ['steak', 'Steak sirloin (6 oz)', 360, 50, 'Protein', 'meat'],
  ['tuna', 'Tuna pouch', 100, 20, 'Protein', 'fish'],
  ['jerky', 'Beef jerky (1 oz)', 80, 13, 'Protein', 'meat'],
  ['tofu', 'Tofu (½ block)', 180, 20, 'Protein', 'veg'],
  ['probar', 'Protein bar', 210, 20, 'Protein', 'veg'],
  ['milk2', 'Milk 2% (2 cups)', 240, 16, 'Protein', 'veg'],
  // Dining hall
  ['dh_plate', 'Dining plate: chicken, rice, veg', 600, 45, 'Dining hall', 'meat'],
  ['dh_salad', 'Salad bar + grilled chicken', 420, 38, 'Dining hall', 'meat'],
  ['dh_stirfry', 'Stir-fry bowl (chicken)', 650, 40, 'Dining hall', 'meat'],
  ['dh_pasta', 'Pasta + marinara (2 cups)', 500, 16, 'Dining hall', 'veg'],
  ['dh_pastameat', 'Pasta + meat sauce (2 cups)', 650, 32, 'Dining hall', 'meat'],
  ['dh_burger', 'Cheeseburger (grill)', 550, 30, 'Dining hall', 'meat'],
  ['dh_pizza', 'Pizza slice (pepperoni)', 310, 13, 'Dining hall', 'meat'],
  ['dh_cheesepizza', 'Pizza slice (cheese)', 285, 12, 'Dining hall', 'veg'],
  ['dh_turkeysand', 'Deli turkey sandwich', 380, 26, 'Dining hall', 'meat'],
  ['dh_rice', 'Rice (1 cup)', 205, 4, 'Dining hall', 'veg'],
  ['dh_potato', 'Baked potato (plain)', 160, 4, 'Dining hall', 'veg'],
  ['dh_veg', 'Roasted vegetables (1 cup)', 100, 3, 'Dining hall', 'veg'],
  ['dh_tacos', 'Tacos ×2 (chicken)', 420, 28, 'Dining hall', 'meat'],
  // Fast food
  ['chip_bowl', 'Chipotle chicken bowl (rice, beans, salsa)', 660, 52, 'Fast food', 'meat'],
  ['chip_burrito', 'Chipotle chicken burrito', 1050, 58, 'Fast food', 'meat'],
  ['cfa_nug8', 'Chick-fil-A grilled nuggets (8 ct)', 130, 25, 'Fast food', 'meat'],
  ['cfa_nug12', 'Chick-fil-A grilled nuggets (12 ct)', 200, 38, 'Fast food', 'meat'],
  ['cfa_sand', 'Chick-fil-A chicken sandwich', 440, 28, 'Fast food', 'meat'],
  ['cfa_grillsand', 'Chick-fil-A grilled sandwich', 390, 28, 'Fast food', 'meat'],
  ['sub_turkey', 'Subway 6" turkey', 280, 18, 'Fast food', 'meat'],
  ['sub_chicken', 'Subway footlong chicken', 640, 52, 'Fast food', 'meat'],
  ['panda_teri', 'Panda bowl: teriyaki chicken + veggies', 420, 40, 'Fast food', 'meat'],
  ['panda_orange', 'Panda plate: orange chicken + fried rice', 1010, 30, 'Fast food', 'meat'],
  ['mcd_dbl', 'McDonald’s McDouble', 400, 22, 'Fast food', 'meat'],
  ['wendys_chili', 'Wendy’s chili (large)', 340, 23, 'Fast food', 'meat'],
  // Breakfast
  ['oats', 'Oatmeal (1 cup cooked)', 160, 6, 'Breakfast', 'veg'],
  ['bagel_cc', 'Bagel + cream cheese', 450, 13, 'Breakfast', 'veg'],
  ['cereal', 'Cereal + milk (bowl)', 300, 10, 'Breakfast', 'veg'],
  ['eggbites', 'Starbucks egg bites (bacon)', 300, 19, 'Breakfast', 'meat'],
  ['bfast_burrito', 'Breakfast burrito', 550, 25, 'Breakfast', 'meat'],
  ['pb_toast', 'PB toast (2 slices)', 380, 14, 'Breakfast', 'veg'],
  // Snacks
  ['banana', 'Banana', 105, 1, 'Snacks', 'veg'],
  ['apple', 'Apple', 95, 0, 'Snacks', 'veg'],
  ['pbj', 'PB&J sandwich', 380, 13, 'Snacks', 'veg'],
  ['pb2', 'Peanut butter (2 tbsp)', 190, 8, 'Snacks', 'veg'],
  ['stringcheese', 'String cheese', 80, 7, 'Snacks', 'veg'],
  ['trailmix', 'Trail mix (¼ cup)', 175, 5, 'Snacks', 'veg'],
  ['chips', 'Chips (1 bag, 1 oz)', 160, 2, 'Snacks', 'veg'],
  ['ricecake', 'Rice cakes ×2', 70, 1, 'Snacks', 'veg'],
  ['popcorn', 'Popcorn (3 cups air-popped)', 95, 3, 'Snacks', 'veg'],
  ['cookie', 'Cookie (dining hall)', 220, 2, 'Snacks', 'veg'],
  // Drinks
  ['latte', 'Latte grande (2%)', 190, 13, 'Drinks', 'veg'],
  ['chocmilk', 'Chocolate milk (1 cup)', 200, 8, 'Drinks', 'veg'],
  ['oj', 'Orange juice (12 oz)', 165, 2, 'Drinks', 'veg'],
  ['soda', 'Soda (12 oz)', 140, 0, 'Drinks', 'veg'],
  ['gatorade', 'Gatorade (20 oz)', 140, 0, 'Drinks', 'veg'],
  ['beer', 'Beer (12 oz)', 150, 1, 'Drinks', 'veg'],
  ['lightbeer', 'Light beer (12 oz)', 100, 1, 'Drinks', 'veg'],
].map(([id, n, kcal, p, cat, diet]) => ({ id, n, kcal, p, cat, diet }));
const MEALS = [['breakfast', 'Breakfast', '🍳'], ['lunch', 'Lunch', '🥗'], ['dinner', 'Dinner', '🍽️'], ['snack', 'Snack', '🍎']];
